# Generated by Django 5.1.1 on 2024-09-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sintomas', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_menstruales', to='decisiones.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('decision', models.TextField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('estado_animo', models.CharField(max_length=50)),
                ('premenstrual', models.BooleanField(default=False)),
                ('evento_inusual', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='decisiones.usuario')),
            ],
        ),
    ]
